# Tunnel Client Configuration

# Client identification
client_id: "server1"

# Server connection
server:
  # Tunnel server address
  host: "tunnel.yourdomain.com"
  port: 2222

# SSH settings
ssh:
  # SSH private key for authentication
  private_key_path: "keys/client_ed25519_key"
  
  # Known hosts file (optional)
  known_hosts_path: "keys/known_hosts"
  
  # Strict host key checking
  strict_host_checking: false

# Local services to tunnel
tunnels:
  # SSH access to this server
  - name: "ssh"
    local_host: "127.0.0.1"
    local_port: 22
    protocol: "tcp"
    
  # Web server (optional)
  - name: "web"
    local_host: "127.0.0.1"
    local_port: 80
    protocol: "http"
    
  # Custom service (example)
  # - name: "api"
  #   local_host: "127.0.0.1"
  #   local_port: 3000
  #   protocol: "tcp"

# Connection settings
connection:
  # Reconnection settings
  retry_interval: "10s"
  max_retries: 0  # 0 = infinite retries
  
  # Keep-alive settings
  keepalive_interval: "30s"
  keepalive_timeout: "10s"
  
  # Connection timeout
  connect_timeout: "15s"

# Logging
logging:
  level: "info"  # debug, info, warn, error
  format: "text" # json, text
  file: "logs/tunnel-client.log"

# Health monitoring
health:
  # Enable local health endpoint
  enabled: true
  port: 8081
  
  # Report system metrics to server
  report_metrics: true
  metrics_interval: "60s"

# System service settings (for auto-startup)
service:
  # User to run as (for systemd)
  user: "tunnel"
  
  # Working directory
  working_directory: "/opt/tunnel-client"
  
  # Restart policy
  restart_policy: "always"
